version: "3"

services:
  app:
    image: simplycodedsoftware/ci:7.3
    container_name: "ecotone_example"
    volumes:
      - "$PWD:/data/app"
    user: 1000:1000
    working_dir: "/data/app"
    command: sleep 99999
    networks:
      - default
  rabbitmq:
    image: rabbitmq:3.6-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - default
  database:
    image: postgres:12.1
    networks:
      - default
    environment:
      POSTGRES_USER: "ecotone"
      POSTGRES_PASSWORD: "secret"